/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef price_CONSTANTS_H
#define price_CONSTANTS_H

#include "price_types.h"

namespace tutorial {

class priceConstants {
 public:
  priceConstants();

};

extern const priceConstants g_price_constants;

} // namespace

#endif
