/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "price_constants.h"

namespace tutorial {

const priceConstants g_price_constants;

priceConstants::priceConstants() {
}

} // namespace

